-- . DQL (Data Query Language): Used to retrieve data.

-- SELECT IS USED TO RETRIVE THE DATA FROM THE TABLE 
SELECT * FROM EMPLOYEES;
SELECT * FROM PROJECTS;
SELECT * FROM DEPARTMENTS;

SELECT NAME , SALARY 
FROM EMPLOYEES;

SELECT NAME , DEPTID, SALARY
FROM EMPLOYEES;

SELECT EMPID , NAME, DEPTID, SALARY
FROM EMPLOYEES;

SELECT * FROM EMPLOYEES;

 -- ANNUAL SALARY OF EMPLOYEES
 SELECT SALARY *12 AS ANNUAL_SAL
 FROM EMPLOYEES;
 
 -- NAME , AND HALF TERM SAL 
 SELECT NAME , SALARY, SALARY*6 AS HALF_TERM
 FROM EMPLOYEES;

-- NAME SAL AND 8% HILE IN SAL
SELECT NAME , SALARY , SALARY + SALARY*8 / 100  AS HIKE
FROM EMPLOYEES;
 -- NAME SAL 5% DEDUCTION IN SAL 
 SELECT NAME , SALARY , SALARY - SALARY*5/100 AS DEDUCTION 
 FROM EMPLOYEES;
 
-- NAME , DEPTID , HALFTERMSAL
SELECT NAME , DEPTID, SALARY*6 AS HALF_TERM
FROM EMPLOYEES; 
-- ALL EMP DETAIL WITH ANNUAL BONUS OF 2000
SELECT * , SALARY *12 +2000
FROM EMPLOYEES; 

-- SAL , SAL WITH HIKE 10%
SELECT SALARY , SALARY+SALARY*10/100
FROM EMPLOYEES;

-- NAME , SALARY , DEDUDUCTION WITH 25%
SELECT NAME , SALARY , SALARY-SALARY*25/100
FROM EMPLOYEES;

-- DISTINCT IS USED TO REMOVE DUPLICATE VALUES , IT RETURNS ONLY UNIQUE values
SELECT DISTINCT DEPTID, DName
FROM Departments;

SELECT SALARY , DEPTID
FROM employees;
-- from-  it goes to the database search for the table and put the table under execution
-- where it is used to filter condition

select *
from employees
where salary >50000;

-- Using your Employees table, write a query to display only: Name Salary for employees whose DeptID is 103

select name , salary
from employees
where deptid = 103;

SELECT Name
FROM Employees
WHERE Salary <= 48000;

SELECT SALARY*12
FROM EMPLOYEES
WHERE NAME = 'ANITA KAPOOR';

SELECT * 
FROM EMPLOYEES
WHERE JOB = 'CLERK';

SELECT *
FROM EMPLOYEES
WHERE SALARY > 92000;

-- EMP WHO ARE HIRED AFTER 2020
SELECT * 
FROM EMPLOYEES 
WHERE HIREDATE > 2021-04-09 ;

SELECT DEPTID, NAME AS EMPLOYEE_NAME , JOB AS DESIGNATION , SALARY
FROM EMPLOYEES
WHERE DEPTID = 101;

SELECT DEPTID, NAME AS EMPLOYEE_NAME , JOB AS DESIGNATION , SALARY
FROM EMPLOYEES
WHERE DEPTID = 103
ORDER BY SALARY DESC
LIMIT 3;

SELECT DEPTID, NAME AS EMPLOYEE_NAME , JOB AS DESIGNATION , SALARY
FROM EMPLOYEES
WHERE DEPTID = 104 AND SALARY > 45000
ORDER BY NAME ASC;

SELECT DEPTID, NAME AS EMPLOYEE_NAME , JOB AS DESIGNATION , SALARY , HIREDATE
FROM EMPLOYEES
WHERE DEPTID = 101 AND SALARY >= 70000
ORDER BY SALARY DESC
LIMIT 2;

SELECT Name, HireDate
FROM Employees
WHERE HireDate > '2020-12-31';

select name , salary, hiredate
from employees
where hiredate between '2020-12-31' and '2022-12-31';

select * 
from employees
where hiredate > '2023-01-01';

-- ORDER BY CLAUSE IS USED TO SORT THE RESULT SET IN ASEC OR desc
SELECT EMPID ,NAME ,SALARY , JOB
FROM EMPLOYEES
order by SALARY DESC;

SELECT EMPID ,NAME ,SALARY , JOB
FROM EMPLOYEES
order by SALARY ASC;

SELECT NAME , DEPTID , SALARY
FROM EMPLOYEES
ORDER BY DEPTID ASC , SALARY DESC ;

SELECT NAME , JOB , SALARY 
FROM EMPLOYEES
ORDER BY 3 DESC;

SELECT NAME , DEPTID , SALARY
FROM EMPLOYEES
ORDER BY DEPTID ASC , SALARY DESC; 

-- LIMIT 
-- SELECT column_name FROM table_name ORDER BY COLUNM_NAME LIMIT number;

SELECT * FROM EMPLOYEES LIMIT 10;

SELECT NAME , SALARY 
FROM EMPLOYEES
ORDER BY SALARY DESC
LIMIT 5;

SELECT NAME , SALARY
FROM EMPLOYEES
ORDER BY SALARY ASC
LIMIT 3;

-- LIMIT offset, number_of_rows; Skip the first 5 rows Return the next 5 rows

SELECT Name, Salary
FROM Employees
ORDER BY Salary DESC
LIMIT 5, 5;

SELECT MAX(Salary)
FROM Employees;

-- ALIAS AS SELECT column_name AS alias_name FROM table_name;
SELECT Name AS EMPLOYEE_NAME ,
       Salary AS Monthly_Salary
FROM Employees;

-- ----------------------------------
select name as EMPLOYEE_NMAE , JOB AS DESIGNATION , SALARY , HIREDATE
FROM EMPLOYEES
WHERE DEPTID =105
ORDER BY SALARY DESC
LIMIT 5;

select name as EMPLOYEE_NMAE ,  HIREDATE
FROM EMPLOYEES
ORDER BY HIREDATE ASC
LIMIT 4;

-- ------------- execution order ---------------
-- The logical processing order is  
-- FROM
--  ↓
-- WHERE
--  ↓
-- GROUP BY
--  ↓
-- HAVING
--  ↓
-- SELECT
--  ↓
-- DISTINCT
--  ↓
-- ORDER BY
--  ↓
-- LIMIT 

-- Aggregate functions are not allowed because WHERE filters rows before grouping.
-- Aliases are not allowed because WHERE executes before SELECT, so aliases don't exist yet.

select name, avg(salary) as avgsalary
from employees
group by deptid;



 


SELECT DeptID
FROM Employees
GROUP BY DeptID
HAVING SUM(Salary) > 50000;

SELECT Name,
Salary * 12 AS AnnualSalary
FROM Employees
ORDER BY AnnualSalary DESC;







