-- SQL Operators
-- Arithmetic: +, -, *, /, %
-- Comparison: =, >, <, >=, <=, <>, !=
-- Logical: AND, OR, NOT
-- Membership: IN, NOT IN
-- Range: BETWEEN, NOT BETWEEN
-- Pattern Matching: LIKE, NOT LIKE
-- NULL: IS NULL, IS NOT NULL

use company_db;
-- AND OPERATOR IS USED WHEN ALL CONDITION MUST BE TRUE 
SELECT NAME AS EMPLOYEE_NAME , JOB AS DESIGNATION, SALARY
FROM EMPLOYEES
WHERE DEPTID = 101 AND SALARY >70000
ORDER BY SALARY DESC;

SELECT * 
FROM EMPLOYEES 
WHERE JOB = 'MANAGER' AND DEPTID = 101;

SELECT * 
FROM EMPLOYEES 
WHERE JOB = 'MANAGER' AND SALARY >=90000;

SELECT * FROM EMPLOYEES WHERE SALARY > 50000 AND SALARY <90000;

SELECT NAME , SALARY , HIREDATE 
FROM EMPLOYEES 
WHERE HIREDATE > '2020-12-31' AND HIREDATE < '2023-12-31' ;

-- WORKS AS CLERK HIRED  EARNS MORE THAN 45000 AND LESS THAN 86000 EMP HIRED AFTER 2024 AND BEFORE 2020
SELECT *
FROM EMPLOYEES
WHERE JOB = 'CLERK' AND SALARY >45000 AND SALARY <86000 AND HIREDATE > '2020-12-31' AND HIREDATE < '2025-12-31';
----------------------------------------------------------------------------------------------------------------
-- OR IS USED WENEVER WE HAVE TO SATISFY ONLY ONE CONDITION or IT RETURN TRUE IF IT SATISFY ONLY ONE CONDITION
 
 SELECT NAME AS EMPLOYEE_NAME , JOB AS DESIGNATION, SALARY
FROM EMPLOYEES
WHERE DEPTID = 101 OR DEPTID = 103
ORDER BY DEPTID ASC , SALARY DESC;
------------------------------------------------------------------------------------------------------------------
-- NOT IS USED TO EXCLUED OR REVERSE CONDITION
 SELECT *
FROM Employees
WHERE NOT DeptID = 101 AND NOT DEPTID = 103;

SELECT NAME , DEPTID
FROM Employees
WHERE NOT DeptID = 101;
------------------------------------------------------------------------------------------------------------------
-- IN IS MULTIVALUED OPERATOR WHICH ACCEPTS MULTIPLE VALUES IN RHS , 
-- IT IS SHORTCUT FOR MULTIPLE OR OPERATOR
SELECT *
FROM EMPLOYEES WHERE DEPTID IN (101 , 102 , 106)
ORDER BY DEPTID; 

-- NOT IN SIMILAR TO IN OPERATOR , INSTEAD OF SLEECTING NOT IN IS USED TO REJECT THE VALUES 
SELECT * FROM EMPLOYEES WHERE JOB NOT IN ('MANAGER','SALES');

SELECT NAME , DEPTID , SALARY
FROM EMPLOYEES
WHERE DEPTID NOT IN (101,103,105) ORDER BY DEPTID , SALARY DESC;
------------------------------------------------------------------------------------------------------------------
-- BETWEEN OP IS USED INCLUDE BOTH STARTING AND ENDING VALUES , WE USE BETWEEN DURING RANGE VALUES
SELECT Name, Salary, JOB
FROM Employees
WHERE Salary BETWEEN 60000 AND 90000
ORDER BY SALARY DESC;

-- NOT BETWEEN IS USED TO REJECT THE RANGE OF VALUES
SELECT NAME , SALARY JOB 
FROM EMPLOYEES 
WHERE  Salary NOT BETWEEN 60000 AND 90000;
----------------------------------------------------------------------------------------------------------------------
-- LIKE IS USED TO SEARCH FOR PATTERNS IN TEXT
-- INSTEAD OF SEARCHING FOR EXCAT VALUE SERACH PSRT OF A STRING
-- % ACCEPTS N NO OF CHARACTERS , ANY NO OF TIMES OR ANY NO OF CHARACTERS
-- _ ACCEPTS EXCATLY ONE CHARACTER

SELECT * FROM EMPLOYEES WHERE NAME LIKE '%A%';  

SELECT * FROM EMPLOYEES WHERE NAME LIKE 'A%';  
SELECT * FROM EMPLOYEES WHERE NAME LIKE '%A';  
-- Exactly 5-letter names starting with 'A'
SELECT * FROM EMPLOYEES WHERE Name LIKE 'A____'; 

SELECT NAME , JOB 
FROM EMPLOYEES WHERE NAME LIKE 'A%'
ORDER BY NAME;
-----------------------------------------------------------------------------------------------------------------------
-- ISNULL - CHECKS WHICH VALUES ARE NULL VALUES OR MISSING UNKNOWN VALUES AND RETURNS IT
select NAME , MANAGERID FROM EMPLOYEES WHERE MANAGERID IS NULL ORDER BY NAME ;
-- IS NOT NULL - It returns rows where the column contains a value.
select NAME , MANAGERID , DEPTID FROM EMPLOYEES WHERE MANAGERID IS NOT NULL ORDER BY DEPTID , NAME;

--------------------------------------------------------------------------------------------

